[package]
name = "retroboy-sdl"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[package.metadata.bundle]
name = "RetroBoy"
identifier = "com.retroboy.emulator"
category = "Game"

[dependencies.retroboy]
path = "../../"

[dependencies]
sdl2 = "0.37"
rfd = "0.14"